
on:
  workflow_dispatch:

jobs:
  job_1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [14.x, 15.x, 16.x, 20.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup node runtime
        uses: actions/setup-node@v6.2.0
        with:
          node_version: ${{ matrix.node_version }}
      
        
